name: Compilar .NET #Nome do WorkFlow

on: # local onde será definido os gatilhos
  push: 
    branches: 
      - main

jobs:
  build: #nome do job
    runs-on: ubuntu-latest #onde será executado o trabalho
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps: # passos do trabalho
      - name: Checkout # nome da etapa, aqui o repo do Git é clonado na maquina virtual.
        uses: actions/checkout@v3
        with:
          ref: 'main' #not naming the ref will fetch the default branch
          fetch-depth: '1' #1 is default and 0 fetches the full depth of the repo
      
      - name: build
        run: dotnet build --no-restore

      - name: Teste
        run: dotnet test --no-build --verbosity normal