name: Compilar .NET #Nome do WorkFlow

on: # local onde será definido os gatilhos
  push: 
    branches: 
      - main

jobs:
  build: #nome do job
    runs-on: ubuntu-latest #onde será executado o trabalho

    steps: # passos do trabalho
      - name: Checkout # nome da etapa, aqui o repo do Git é clonado na maquina virtual.
        uses: actions/checkout@v3
        with:
          ref: 'main' #not naming the ref will fetch the default branch
          fetch-depth: '1' #1 is default and 0 fetches the full depth of the repo
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependence
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: Teste
        run: dotnet test --no-build --verbosy normal